### ISSUE TITLE
Please Explain the Presenters, what is the purpose of creating them ?

### ISSUE THREAD

**Issue by himtweety** [langaner/phalcon-micro-starter#1]
I have implemented your base application for testing use in my application and understood the use of service and repositories in Model using App Provider but unable to understand why you used presenter

**Comment by langaner** [comment]
Presenters need only for decorate model to display data differently from how it is stored in database. 
For example need to show full name of user included first name, last name etc. 
Presenters implementation in starter is not good, but allows you to transfer part of the logic from the models. When there will be a free time I will try to make presenters more useful ))

**Comment by himtweety** [comment]
Thanks for quick response.. Me too was planning to use the implementation without presenters. Found one more issue on the app framework, magi  getter setters not working for Models but looks like that is the issue on phalcon side

**Comment by himtweety** [comment]
If you have any implementation suggestions or quick fix regarding that please share
